name: "inkomoko_assessment"
version: "1.0.0"
config-version: 2

profile: "inkomoko_assessment"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  inkomoko_assessment:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
